### ISSUE TITLE
Constant "insufficient fee" errors

### ISSUE THREAD

**Issue by ZuluSpl0it** [terra-rebels/station#15]
OK something is really wrong with columbus-5. I've been fighting the "insufficient fee" error for at least three days now. I have plenty of LUNC and USTC in the wallet but it still fails. I tried "Terra Station" webpage and chrome extension. I've also tried "Rebel Station" webpage, chrome extension and desktop app. The contract works fine on the testnet. 

I cloned the rebel-station repo in order to raise the fee paid within the code. But no matter how high I go, I still get the "insufficient fee" error. For example, in the constants.ts file I changed "export const CLASSIC_DEFAULT_GAS_ADJUSTMENT = 3" to "export const CLASSIC_DEFAULT_GAS_ADJUSTMENT = 20". The LUNC fee went from 4.526976 LUNC to 30.198529 LUNC, and the USTC fee went from 0.119867 USTC to 0.799608 USTC. Still fails! That's a 6.67X increase and still getting the "insufficient fee" error. I included screenshots. Devs are trying to bring utility back to Terra Classic, but issues like this will drive us away. Especially since our smart contracts work just fine on Terra 2.

The smart contract is: terra1r8t57xzx4ekwc6ts7nc8cg0gsg7jrpf9pwmnug

All of these queries/executes work fine: {"curve_info":{}}, {"token_info":{}}, {"marketing_info":{}}, {"buy_sell":{}}, {"minter":{}}, {"download_logo":{}}, update_buy_sell, update_buy_sell

I get  "insufficient fee" error for {"buy":{}} and therefore haven't been able to try the burn execute.

![image](https://user-images.githubusercontent.com/55359362/208829075-139a4bdf-a264-49d0-a001-53553f5ed086.png)
![image](https://user-images.githubusercontent.com/55359362/208829106-351c7c61-dc12-4ef8-b889-c2577e6026b3.png)

**Comment by Raider7019** [comment]
Please can you provide a smart contract address for this contract on the Rebel-2 testnet (LCD = https://rebel1.grouptwo.org)?

**Comment by ZuluSpl0it** [comment]
Just to make sure I understand the networks: 
Classic (mainnet) is columbus-5 and Rebel-2 (testnet for classic) is rebel-2

I'm unable to load the contract onto rebel-2 (LCD = https://rebel1.grouptwo.org/) because it gives "Transaction is not available" when uploading the wasm.  Or it will give me a "[DecimalError] Invalid argument: undefined" error while uploading.

However, the smart contract is stored on Classic (columbus-5). That is the one that is giving the "insufficient fee" error when trying to "buy". All other functions work and don't give the "insufficient fee" error.
![Picture1](https://user-images.githubusercontent.com/55359362/208966421-00b321d8-372d-452a-8bb3-2a4b0908e2e7.jpg)

The contract on columbus-5 (Classic mainnet) is: terra1r8t57xzx4ekwc6ts7nc8cg0gsg7jrpf9pwmnug
![Picture2](https://user-images.githubusercontent.com/55359362/208966493-d7366269-5bb0-4af4-a285-54c3310f0764.jpg)


The contract also works on Terra 2 Testnet: terra1n53a58ukjcpa2qnweqax5p5tfgekx3jm5747sp9c2cewv3s2hjasycm0hr (This one works 100%, but it's on Terra 2)


![Picture1](https://user-images.githubusercontent.com/55359362/208966590-9c9b532e-9346-4550-923b-86581e60e68f.jpg)
![Picture2](https://user-images.githubusercontent.com/55359362/208966606-0dfb41e6-01d0-4a02-892e-de9d83168042.jpg)

**Comment by ZuluSpl0it** [comment]
Just to make sure I understand the networks: 
Classic (mainnet) is columbus-5 and Rebel-2 (testnet for classic) is rebel-2

I'm unable to load the contract onto rebel-2 (LCD = https://rebel1.grouptwo.org/) because it gives "Transaction is not available" when uploading the wasm.  Or it will give me a "[DecimalError] Invalid argument: undefined" error while uploading.

However, the smart contract is stored on Classic (columbus-5). That is the one that is giving the "insufficient fee" error when trying to "buy". All other functions work and don't give the "insufficient fee" error.

The contract on columbus-5 (Classic mainnet) is: terra1r8t57xzx4ekwc6ts7nc8cg0gsg7jrpf9pwmnug

The contract also works on Terra 2 Testnet: terra1n53a58ukjcpa2qnweqax5p5tfgekx3jm5747sp9c2cewv3s2hjasycm0hr (This one works 100%, but it's on Terra 2)

![Picture1](https://user-images.githubusercontent.com/55359362/208966818-2bf9897e-fad0-4669-9110-68767a2d40b8.jpg)

![Picture2](https://user-images.githubusercontent.com/55359362/208966844-fc8ed14c-e4b5-496a-841b-0157cf3daae3.jpg)

**Comment by ZuluSpl0it** [comment]
The code for the contract is at: https://github.com/ZuluSpl0it/contracts/tree/main/contracts/cw20-bonding

To compile, run the following from the cw20-bonding directory

RUSTFLAGS="-C link-arg=-s" cargo build --release --target=wasm32-unknown-unknown --locked

**Comment by Raider7019** [comment]
Thanks for the responses. I'll investigate further.

**Comment by Raider7019** [comment]
This looks to be the result of an existing bug in the LCD simulate endpoint (layer 1 code) in the handling of gas and fee estimation, rather than an issue with Station. This issue is currently planned to be resolved by the new L1 taskforce in release 1.0.5: https://classic-agora.terra.money/t/joint-l1-task-force/49108
